name: ai-habit-rewriter
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - gradio>=4.0.0,<6.0.0
    - transformers>=4.20.0,<5.0.0
    - torch>=1.12.0,<3.0.0
    - fpdf>=1.7.0,<3.0.0 
